### ISSUE TITLE
Aggregated jump callback resetting

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqJump.jl#119]
It would be nice to be able to "reset", i.e. rebuild the rates and take new random numbers. That is the blocker on https://github.com/SciML/DiffEqJump.jl/issues/78 and https://github.com/PumasAI/Pumas.jl/pull/472 . I am envisioning a function like `reset_jumps!(cb)` which does nothing on a non-JumpCallback (so that we can apply it to the full `CallbackSet`) but then regenerates everything, so that if a `DiscreteCallback` or `ContinuousCallback` is used to perturb the system we can `reset_jumps!(integrator.callback)`.

@isaacsas I think this would have to be implemented per-aggregator, but could have a generic fallback?

**Comment by isaacsas** [comment]
An inefficient way would be to just call:
https://github.com/SciML/DiffEqJump.jl/blob/ee225e7f9773b2d87734179c245fed77ba331b92/src/aggregators/direct.jl#L35
I think.

Knowing which state variables have changed would allow us to much more efficiently update some methods.

**Comment by isaacsas** [comment]
We should probably move the time generation call out of that and into `initialize!`, then the latter could be called.

**Comment by ChrisRackauckas** [comment]
I think that function probably works. I can probably whip something up in a bit. Dependency analysis on a callback might be tricky though, but we could make a scheme for that later.

**Comment by isaacsas** [comment]
It would just be looking at `u` vs `hold` and seeing which entries have changed.

**Comment by isaacsas** [comment]
`uold` I mean.
