### ISSUE TITLE
Optimization of RejectionDirect

### ISSUE THREAD

**Issue by Vilin97** [SciML/DiffEqJump.jl#123]
Rejection Direct is a method, which replaces the linear search for the next reaction in Direct with rejection sampling. In order to do this, the variable `max_rate` is stored in the aggregator. In order for the method to work correctly, `max_rate` must always be at least as big as the highest propensity over all reactions. At the same time, the smaller `max_rate` is, the fewer rejections there will be, and the faster the method will perform. The challenge is to maintain `max_rate` to have a good balance between these two. It is clear when to increase it: whenever any propensity gets bigger than `max_rate`. The question of when to decrease it is uncertain. 
There are two extremes: if `max_rate` is updated every time a reaction fires (which is close to what is being done now, although not quite), too much time (linear in number of reactions) will be spent on this update. If it is never updated, the method will perform poorly (e.g. in the extinction network, where one species is going extinct). An approach suggested by @isaacsas is to keep a counter and update `max_rate` every `update_frequency` steps, where `update_frequency` is some heuristic parameter (or perhaps is somehow inferred from the network at the initialization step). 
A good strategy needs to be developed and benchmarks on networks with different propensity distributions need to be done.

**Comment by Vilin97** [comment]
Doing K rejections takes about 60 times more time than doing `maximum(rates)` for K rates. In other words, for a network of K reactions it is worth doing an update if it saves over 60*K rejections (i.e. that many rejections are eliminated).

**Comment by isaacsas** [comment]
How big is K when you tested this?

**Comment by Vilin97** [comment]
I tested up to K=10^8. My computers had trouble generating ~10^9 random numbers.

**Comment by Vilin97** [comment]
The current strategy I think will work best is to simply update the max_rate if the number of rejection to sample the previous reaction was more than c*K, where c is some pre-set parameter that I will need to find a good value for (it is definitely at least 1). The pros of this approach are: 
1. It's simple: only one counter is needed, and is reset each step of the simulation.
2. It is flexible: if max_rate is equal to the maximum of the current rates, then the number of rejections is equal to max_rate/(sum of rates) in expectation. Thus, it is at most K in expectation, since (sum of rates) <= (maximum of rates). Also, the probability of seeing over c*K rejections is exponentially small in c (it is at most e^{-c}). Thus, max_rate will only be updated when actually needed.
3. It does not have weird edge cases to consider. The decision whether to recompute max_rate is made after every jump, and thus there is no situation when the maximum of rates is way smaller than max_rate, which would be bad for the runtime.

The question is how to pick the parameter c.

**Comment by Vilin97** [comment]
I did some benchmarking and found out that as long as the threshold c is reasonable (somewhere between 0.1 and 10), the running time does not change much. Looking at the profiler, I see that the reason for this is that rejections and finding the maximim of rates just don't account for that big portion of the runtime. It also seems pretty network-dependent. For example, for the 1D diffusion network it is best to set the threshold very high, since the rates are very uniform, and so max_rate should ideally be almost never recalculated. On the other hand, the optimal threshold for the gene expression network is actually 1 or 2, i.e. max_rate is recalculated if more than 1 or 2 rejections happened in the sampling. I think setting the default c = 1 is not a bad choice. This still leaves the freedom to set a custom threshold if the user so desires.

Another heuristic that might perform better is to let the threshold vary based on the value of current `max_rate` and `sum(rates)` instead of fixing it at c * K. The reason this might perform better is that the expected number of rejections is equal to `max_rate/mean(rates) = K * max_rate/sum(rates)`. Thus, the sum of rates might be the more relevant number compare the number of rejections to. For example, a reasonable strategy is to update `max_rate` when the number of rejections exceeded `c * K * max_rate/sum(rates)` for some `c`. This is harder to analyze but might perform better for networks, where rates vary a lot (although `RDirect` probably should not be used on those).

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/DiffEqJump.jl/pull/140
