### ISSUE TITLE
Interface for spatial problems

### ISSUE THREAD

**Issue by Vilin97** [SciML/DiffEqJump.jl#130]
I have written a script that, given a DiGraph (presented as an adjacency list), rates of diffusion for each species for each edge, mass action jumps, a DiscreteProblem and an SSA, constructs a spatial version of the problem that can be fed into any SSA to solve. The signature of the function that does the conversion is 
`function to_spatial_jump_prob(connectivity_list, diff_rates, massaction_jump :: MassActionJump, prob :: DiscreteProblem, alg; save_positions = (false, false), starting_state = nothing, get_rate = nothing, assign_products = nothing)`.
To be clear, this function only works if all jumps are mass action jumps. There is functionality to have neighboring nodes react as well, by providing the `get_rate ` and `assign_products` functions (the first must give the rate of reaction between two neighbors, and the other must assign the products of the reaction). If these two functions are passed in, only uni- and bimolecular reactions are allowed.
Since DiffEqJump.jl will likely get specialized spatial solvers in the future it might be good to think of a unified interface for solving spatial problems. For example, there could be a function `solve_spatial` that takes in a DiGraph, diffusion rates, mass action jumps, the final time, and some optional arguments and solves the spatial variant of the problem. Then I can wrap the function I have to adhere to this interface and open a PR. 
I am not familiar with the Modeling Toolkit but from what I understand, it has some of the same functionality as the function I wrote, except it takes unreasonably long to set up the problem, as mentioned in https://discourse.julialang.org/t/lightgraph-modeltoolkit-optimization/40696/60. My function takes milliseconds to set up the spatial problem even for large problems.

https://github.com/Vilin97/DiffEqJump.jl/blob/Spatial/test/spatial/ABC.jl is an example of using the `to_spatial_jump_prob` interface for the network A+B <--> C with diffusion and the graph representing a cube of sites in R^3. https://github.com/Vilin97/DiffEqJump.jl/blob/Spatial/test/spatial/gene_expression.jl is an example of the gene expression problem with diffusion on a cycle graph.

**Comment by isaacsas** [comment]
Related: https://github.com/SciML/Catalyst.jl/issues/229

We should work out the higher level interface for specifying systems, and then work out here how to handle the various types of systems in a clean way. We can build from Vasily's script to get spatial/graph solvers that use the underlying well-mixed SSAs right now, but need to make sure everything is setup in a way that we can also add more specialized solvers down the line.

**Comment by atiyo** [comment]
Is work still being done on above PR?

ModelingToolkit.jl (MTK) has come some way since that PR was opened, and I wondered whether some consistency with how MTK handles PDEs might be useful for structuring how domains and boundary conditions are surfaced to users, cf: https://mtk.sciml.ai/stable/systems/PDESystem/

**Comment by ChrisRackauckas** [comment]
>Would it be helpful to mimic implementations in DiffEqOperators.jl?

Not yet. We're redoing a few things in this space right now. PDESystem is "close", but still experimental. Spatial jump processes should probably start getting big work this summer, which is when PDESystem should be out of an alpha stage and more in beta.

**Comment by Vilin97** [comment]
> Is work still being done on above PR?
Hopefully my GSoC funding gets approved and work will indeed be done on this PR in the upcoming summer.

**Comment by Vilin97** [comment]
Update: the GSoC funding was approved and I began working on this. The first PR https://github.com/SciML/DiffEqJump.jl/pull/183 should establish an interface, which is consistent with the existing interface for non-spatial jump problems. So far, I implemented the Next Subvolume Method, although it still needs more work. There are two tests that show how to set up and solve a spatial jump problem.

**Comment by Vilin97** [comment]
Should this be closed now, given https://github.com/SciML/DiffEqJump.jl/pull/183 and https://github.com/SciML/DiffEqJump.jl/issues/189?
