### ISSUE TITLE
Keep track of tprev and uprev in SSAStepper (for use in callbacks)

### ISSUE THREAD

**Issue by manuel-rhdt** [SciML/DiffEqJump.jl#132]
The [integrator interface](https://diffeq.sciml.ai/dev/basics/integrator/) specifies that an integrator has the fields `tprev` and `uprev` that hold the values of the last time point and last solution value, respectively. I see no reason why `SSAStepper` should not have these fields.

**Comment by manuel-rhdt** [comment]
if there are no objections I wouldn't mind adding these fields myself in a pull request.

**Comment by isaacsas** [comment]
Yeah, please do make a PR.
