### ISSUE TITLE
terminating SSAStepper for exit time problems and such

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqJump.jl#137]
It would be great to be able to have a way to stop SSAStepper when an event occurs like an exit time (and have that event recorded as the final saved time in the solution).

**Comment by isaacsas** [comment]
As a work around I tried the following, which seems to work, modulo that I am confused by `savevalues!` telling me that `saved=false` but `savedexactly=true`. Is that the correct behavior?

```julia
using Catalyst, DiffEqBase, DiffEqJump, DiffEqCallbacks

function extinction_condition(u,t,integrator)   
    integrator.cb.affect!.next_jump_time == Inf
end
function extinction_affect!(integrator)
    (saved, savedexactly) = savevalues!(integrator, true)
    println("saved = $saved, savedexactly=$savedexactly")
    nothing
end
cb = DiscreteCallback(extinction_condition, extinction_affect!, save_positions=(false,false))

rn = @reaction_network begin
    1.0, A --> 0
end
u0 = [10]
tspan = (0.0, 1e5)
dprob = DiscreteProblem(rn, u0, tspan)
jprob = JumpProblem(rn, dprob, Direct(), save_positions=(false,false))
sol = solve(jprob, SSAStepper(), callback=cb)
extinctiontime = sol.t[end-1]
```

**Comment by ChrisRackauckas** [comment]
This should follow the common interface, so it should probably look like:

```julia
condition(u,t,integrator) = all(x->0,u)
affect!(integrator) = terminate!(integrator)
```

which is how other things would work. What we need to do is figure out how to implement `terminate!(integrator)`, which might just be to have a bool that makes it exit its event loop.

**Comment by isaacsas** [comment]
So just check the bool here:
https://github.com/SciML/DiffEqJump.jl/blob/defa950a9310ee9aef5d7bfcd1e156d96a97f386/src/SSA_stepper.jl#L39
 as an condition to continuing iteration and then skip the rest of the post-stepping saving and return?

Also, should here `saved=true` be set too?
https://github.com/SciML/DiffEqJump.jl/blob/defa950a9310ee9aef5d7bfcd1e156d96a97f386/src/SSA_stepper.jl#L188

If that is all that is required I can put in a PR for this.

**Comment by ChrisRackauckas** [comment]
Yup I think that's all.

**Comment by isaacsas** [comment]
Ok, thanks for taking a look! I'm not super up on the general integrator implementation, I couldn't even find where the ODE stepping is handled in general when I took a quick look, so wasn't sure if there are other things that might need to be handled.
