### ISSUE TITLE
Allocations from sizehint! show up in profiles

### ISSUE THREAD

**Issue by manuel-rhdt** [SciML/DiffEqJump.jl#152]
I think the following line is a bad default choice for the preallocation of the solution (currently set to 10000). There is no way a user can change the amount of preallocation while keeping `save_everystep` enabled.

https://github.com/SciML/DiffEqJump.jl/blob/bbc9fc5d06e420f6da1f992b95004e19edf62285/src/SSA_stepper.jl#L127

Specifically, in my project I frequently need to generate short solutions with only a few tens of steps and therefore a lot of too large allocations show up in my profiles. I therefore propose to remove the preallocation code and/or make the amount of preallocation configurable.

P.S.: Ideally I could reuse allocations from previous solutions but I don't think that is possible yet with `JumpProblem` (please correct me if I am mistaken).

**Comment by isaacsas** [comment]
@manuel-rhdt We can add a kwarg to let users specify that.

**Comment by manuel-rhdt** [comment]
@isaacsas Yes that sounds good.

Do you think it is best to leave the _default_ `sizehint!` at 10k as it is currently? In my opinion it makes more sense to just rely on julia's default vector growing strategy (i.e. don't call `sizehint!` at all unless the user specifies the new kwarg). Of course, that could hurt default performance in some cases but probably also increases performance in others. Then, if someone really cares about performance they can set `sizehint!` optimally for their needs.

For me, it is fine either way, but I think it would be more intuitive to disable preallocation by default. Let me know about your thoughts and I can open a PR.

**Comment by ChrisRackauckas** [comment]
putting it more conservatively at something like 100 probably gets 99% of the speedup while making it essentially a non-issue, so I'd accept a PR that changes it
