### ISSUE TITLE
Length of solution does not match expected length with `saveat`

### ISSUE THREAD

**Issue by alanderos91** [SciML/DiffEqJump.jl#157]
It seems that sometimes `length(sol)` does not match `length(saveat)` as expected. This happens whether a range, array, or scalar is used. I checked that the example in #124 matches what I understand to be the correct behavior.
What is strange is that the issue seems tied to `ConstantRateJump`?

Below is an example to reproduce the behavior:

```julia
using DifferentialEquations, DiffEqJump

rate(u,p,t) = 2.0*u[1,1]
affect!(integrator) = (integrator.u[1,2] += 1)
jump = ConstantRateJump(rate, affect!)

M = N = 3
tspan = (0.0, 10.0)
saveat=tspan[1]:0.1:tspan[end]
u0 = zeros(Int, 3, 3); u0[1,1] = 1

prob = DiscreteProblem(u0, tspan)
jump_prob = JumpProblem(prob, Direct(), jump)
sol = DiffEqJump.solve(jump_prob, saveat=saveat)

length(saveat) == length(sol) # false
all(t -> t ∈ sol.t, saveat) # true
```
Here `length(sol)` is random. I don't think this is a major issue since at least all the points in `saveat` are respected. However, this came up in running a much larger problem with `u0` being somewhat large. I imagine the extra saved points scales with the number of jump events simulated over `tspan`, so it would be nice to avoid this behavior.

Relevant info:

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

```
Status `~/Projects/IPSSimComparison/Project.toml`
  [6aabf0a6] BioSimulator v0.9.3 `https://github.com/alanderos91/BioSimulator.jl.git#master`
  [2b5f629d] DiffEqBase v6.44.3
  [eb300fae] DiffEqBiological v4.3.0
  [c894b116] DiffEqJump v6.10.0
  [0c46a032] DifferentialEquations v6.15.0
```

**Comment by ChrisRackauckas** [comment]
`jump_prob = JumpProblem(prob, Direct(), jump,save_positions=(false,false))` because of the discontinuity handling.

**Comment by alanderos91** [comment]
🤦 thanks for the quick response!
