### ISSUE TITLE
Tutorial for resetting and reinitializing jumps, docs for parameter-based MassActionJumps

### ISSUE THREAD

**Issue by isaacsas** [SciML/DiffEqJump.jl#160]
This seems to come up enough that we should make a tutorial with info from

https://discourse.julialang.org/t/simulating-mjps-many-times-with-different-parameters-as-inner-loop/49061/11

and showing how to use 

https://github.com/SciML/DiffEqJump.jl/blob/master/src/aggregators/aggregated_api.jl#L18

(In addition to getting remake working...)

**Comment by ChrisRackauckas** [comment]
Yes, we need to find the right place to document this. It's a bit tricky. It should probably get a mention in the event handling and the Jump area somehow.

**Comment by manuel-rhdt** [comment]
I personally found out that I need to call `reset_aggregated_jumps!` whenever I make changes to `integrator.u` while reading Github issues in this repo. Previous to that I got the impression from the docs that the integrators update their internal state automatically when you change `integrator.u` in a callback. After all, there exists the function `DiffEqBase.u_modified!`.

Therefore I agree that better documentation might help future users to avoid the confusion.

Further, I feel that an important part of the convenience of callbacks comes from the fact that you don't have to care about the integrator's internals, and still get a correct result even if you modify `integrator.u`. Hence, it might be desirable to also be "correct by default" when using callbacks while solving a `JumpProblem` (i.e. without the need of explicitly calling `reset_aggregated_jumps!` in the callback's `affect!`). I think a possible implementation has already been suggested in https://github.com/SciML/DiffEqJump.jl/pull/120#issue-433694975 although I agree it there is non-negligible work involved (and I must admit that I do not feel comfortable to make a pull request along those lines). With that said, I would certainly be in favor of such a change.

**Comment by ChrisRackauckas** [comment]
What should really happen is that this should be moved up in the integrator interface. The definition of the function should be moved to the top level file in DiffEqBase, and this package should then import that. Then, all of the integrators have a check for `u_modified!` and it has different behaviors upon the modification of `u`. The callback handling should just plop this in there as something that is done automatically. If someone wanted to start this progress I can help complete it.

**Comment by isaacsas** [comment]
https://github.com/SciML/DiffEqDocs.jl/pull/428 adds docs on how to update `JumpProblem`s and rates. So that's half the story.

**Comment by isaacsas** [comment]
Going along with this we need to update the main docs to push users towards the new parameter-based MassActionJump version, since they are more amenable to use in callbacks.

**Comment by isaacsas** [comment]
Latest doc updates cover remaking, events and the new MassActionJump format for users.
