### ISSUE TITLE
JumpArray Typing

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqJump.jl#2]
Instead of `Float64`, generalize via triangular dispatch.

**Comment by isaacsas** [comment]
Ok to close? I assume this is something that isn't in the package anymore?

**Comment by ChrisRackauckas** [comment]
It's there, and you can see it doing triangular dispatching https://github.com/SciML/DiffEqJump.jl/blob/master/src/extended_jump_array.jl#L1
