### ISSUE TITLE
Identical Ensemble solutions

### ISSUE THREAD

**Issue by korsbo** [SciML/DiffEqJump.jl#95]
Hi, 
using the Ensemble interface with Jump equations yields multiple identical solutions when they should (most likely) not be.

```julia
using DifferentialEquations
using DiffEqBiological
using Plots

rn = @reaction_network ModelTest begin
    (10., 1.), 0 ↔ X
end

u0 = [0]
prob = DiscreteProblem(u0, (0., 100.), [])
jump_prob = JumpProblem(prob, Direct(), rn)
sol = solve(EnsembleProblem(jump_prob); trajectories=3)

plot(sol)
```

The output of this is three overlapping lines. 

It works fine with SDE problems, so I guessed that the issue should be filed here.

Cheers!

**Comment by isaacsas** [comment]
Do you know what solver is even getting used here? `SSAStepper`, `FunctionMap`? (I'm not particularly familiar with `EnsembleProblem`s.)

More generally, it really seems like rng setup and initialization should be handled in the `EnsembleProblem`. That is the level where uncorrelated generators can be appropriately setup on different threads and/or CPUs using thread/process ids and a global seed.
